version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine  # Usamos Redis como broker

  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/todolist
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True

  celery:
    build: .
    command: celery -A todolist worker --loglevel=info
    volumes:
      - .:/todolist
    depends_on:
      - web
      - redis

volumes:
  postgres_data: