version: '3.8'

services:
  db:
    image: postgres:14
    env_file: './envs/local.env'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    env_file: './envs/local.env'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/todolist
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True

volumes:
  postgres_data: